#!/usr/bin/env python3
"""Exploratory constrained search for an order-n Arrhenius phase-type dwell.

The rigorous sandwich theorem does not depend on this stochastic search. The
script is provided to reproduce the kind of numerical candidate shown in Fig. 5.
For fast deterministic verification of the stored candidate, run
``python scripts/verify_optimum.py`` or ``make optimum``.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np
from scipy.optimize import minimize

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from tempcomp import fpt
from tempcomp.optimum import audit_candidate


def edge_order(n: int) -> list[tuple[int, int]]:
    return [(i, j) for i in range(n) for j in range(n) if i != j]


def sigmoid(x: np.ndarray) -> np.ndarray:
    return 1.0 / (1.0 + np.exp(-np.clip(x, -50.0, 50.0)))


def unpack(v: np.ndarray, n: int, Emax: float) -> tuple[list[tuple[int, int]], np.ndarray, np.ndarray]:
    edges = edge_order(n)
    n_rates = len(edges) + n
    log_rates = np.clip(v[:n_rates], -10.0, 5.0)
    rates = np.exp(log_rates)
    energies = Emax * sigmoid(v[n_rates:])
    return edges, rates, energies


def subgen_and_derivative(v: np.ndarray, n: int, Emax: float) -> tuple[np.ndarray, np.ndarray]:
    edges, rates, energies = unpack(v, n, Emax)
    Q = np.zeros((n, n))
    Qp = np.zeros((n, n))
    for idx, (i, j) in enumerate(edges):
        r = rates[idx]
        rp = r * energies[idx]  # T0=1, so dk/dT = k E / T^2 = k E
        Q[i, j] += r; Q[i, i] -= r
        Qp[i, j] += rp; Qp[i, i] -= rp
    offset = len(edges)
    for i in range(n):
        r = rates[offset + i]
        rp = r * energies[offset + i]
        Q[i, i] -= r
        Qp[i, i] -= rp
    return Q, Qp


def stats(v: np.ndarray, n: int, Emax: float) -> tuple[float, float, float] | None:
    Q, Qp = subgen_and_derivative(v, n, Emax)
    try:
        F = np.linalg.inv(-Q)
    except np.linalg.LinAlgError:
        return None
    one = np.ones(n)
    alpha = np.zeros(n); alpha[0] = 1.0
    mean = alpha @ F @ one
    m2 = 2.0 * alpha @ F @ F @ one
    var = m2 - mean * mean
    if not np.isfinite(mean + var) or mean <= 0 or var <= 0:
        return None
    cv2 = var / (mean * mean)
    R = (alpha @ F @ Qp @ F @ one) / mean
    return float(R), float(cv2), float(np.linalg.cond(Q))


def candidate_from_vector(v: np.ndarray, n: int, R: float, Emax: float, description: str) -> dict:
    edges, rates, energies = unpack(v, n, Emax)
    return {
        "description": description,
        "n": n,
        "R_target": R,
        "T0": 1.0,
        "Emax": Emax,
        "state_entry": 0,
        "transient_edge_order": [list(e) for e in edges],
        "exit_state_order": list(range(n)),
        "rates_at_T0": rates.tolist(),
        "activation_energies": energies.tolist(),
        "notes": [
            "Generated by scripts/optimality_search.py.",
            "This is an audited candidate / upper bound, not a proof of global optimality.",
        ],
    }


def objective(v: np.ndarray, n: int, Emax: float) -> float:
    s = stats(v, n, Emax)
    return 1e6 if s is None else s[1]


def constraint(v: np.ndarray, n: int, R: float, Emax: float) -> float:
    s = stats(v, n, Emax)
    return 1e6 if s is None else s[0] - R


def search(n: int, R: float, Emax: float, restarts: int, seed: int) -> tuple[float, dict | None]:
    rng = np.random.default_rng(seed)
    n_par = 2 * (n * (n - 1) + n)
    best_cv = np.inf
    best_candidate = None
    for restart in range(restarts):
        v0 = rng.normal(0.0, 1.3, n_par)
        # A few structured starts help the n=3,R=2 case converge quickly.
        if n == 3 and restart < max(4, restarts // 5):
            n_rates = n * (n - 1) + n
            v0[:n_rates] = rng.normal(-3.0, 4.0, n_rates)
            v0[n_rates:] = rng.normal(0.0, 5.0, n_rates)
        try:
            res = minimize(
                lambda x: objective(x, n, Emax),
                v0,
                method="SLSQP",
                constraints={"type": "eq", "fun": lambda x: constraint(x, n, R, Emax)},
                options={"maxiter": 250, "ftol": 1e-11, "disp": False},
            )
        except Exception:
            continue
        if not res.success:
            continue
        cand = candidate_from_vector(res.x, n, R, Emax, "Candidate generated by stochastic SLSQP search")
        try:
            audit = audit_candidate(cand, r_tol=0.02)
        except Exception:
            continue
        cv = audit["CV2"]
        if cv < best_cv:
            best_cv = cv
            best_candidate = cand
            print(f"restart {restart}: CV^2={cv:.6f}, R={audit['R_analytic']:.6f}, cond={audit['condition_number']:.2g}", flush=True)
    return best_cv, best_candidate


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("n", type=int, nargs="?", default=3)
    ap.add_argument("R", type=float, nargs="?", default=2.0)
    ap.add_argument("--Emax", type=float, default=12.0)
    ap.add_argument("--restarts", type=int, default=20)
    ap.add_argument("--seed", type=int, default=123)
    ap.add_argument("--write-json", type=Path)
    args = ap.parse_args()
    cv, cand = search(args.n, args.R, args.Emax, args.restarts, args.seed)
    lo, hi = 1.0 / args.n, 1.0 / (args.n - 1)
    if cand is None:
        print(f"No audited candidate found; sandwich is [{lo:.6f}, {hi:.6f}].")
        sys.exit(1)
    audit = audit_candidate(cand, r_tol=0.02)
    print(json.dumps(audit, indent=2, sort_keys=True))
    print(f"n={args.n}, R={args.R}: audited candidate CV^2={cv:.6f}; sandwich=[{lo:.6f}, {hi:.6f}]")
    if args.write_json:
        args.write_json.write_text(json.dumps(cand, indent=2) + "\n", encoding="utf-8")
        print("wrote", args.write_json)


if __name__ == "__main__":
    main()
